# TODO при создании контейнера файл выложить в корневой каталог
version: "3.11"
secrets:
  FLASK_SECRET_KEY:
    external: true
services:
  web:
    build: .
    ports:
      - "8000:5000"
    command: python3 main.py
    environment:
      - DB_HOST=postgres_container
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - FLSK_SECRET_KEY='fghgfdssdfdsgdfhgf'


  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    hostname: postgres_container

