"""all_table

Revision ID: 0ff6966e65db
Revises: 72f8ea3b2ab6
Create Date: 2023-03-16 10:19:26.441671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff6966e65db'
down_revision = '72f8ea3b2ab6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('england_table', 'club_stat_url')
    op.drop_column('france_table', 'club_stat_url')
    op.drop_column('germany_table', 'club_stat_url')
    op.drop_column('italy_table', 'club_stat_url')
    op.drop_column('spain_table', 'club_stat_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spain_table', sa.Column('club_stat_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('italy_table', sa.Column('club_stat_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('germany_table', sa.Column('club_stat_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('france_table', sa.Column('club_stat_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('england_table', sa.Column('club_stat_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
