"""Club_Statistics

Revision ID: 496235bd93f1
Revises: 0ff6966e65db
Create Date: 2023-03-17 16:41:08.825216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496235bd93f1'
down_revision = '0ff6966e65db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics_club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shots_on_target_pct', sa.Float(), nullable=True),
    sa.Column('average_shot_distance', sa.Float(), nullable=True),
    sa.Column('passes_pct', sa.Float(), nullable=True),
    sa.Column('passes_pct_short', sa.Float(), nullable=True),
    sa.Column('passes_pct_medium', sa.Float(), nullable=True),
    sa.Column('passes_pct_long', sa.Float(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('cards_yellow', sa.Integer(), nullable=True),
    sa.Column('goals_per_shot_on_target', sa.Float(), nullable=True),
    sa.Column('sca_per90', sa.Float(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics_club')
    # ### end Alembic commands ###
