"""init

Revision ID: 547538e16e01
Revises: 
Create Date: 2023-03-20 14:57:20.764119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547538e16e01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('england_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('club_name', sa.String(), nullable=True),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('won', sa.Integer(), nullable=True),
    sa.Column('drawn', sa.Integer(), nullable=True),
    sa.Column('lost', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('france_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('club_name', sa.String(), nullable=True),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('won', sa.Integer(), nullable=True),
    sa.Column('drawn', sa.Integer(), nullable=True),
    sa.Column('lost', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('germany_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('club_name', sa.String(), nullable=True),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('won', sa.Integer(), nullable=True),
    sa.Column('drawn', sa.Integer(), nullable=True),
    sa.Column('lost', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('italy_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('club_name', sa.String(), nullable=True),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('won', sa.Integer(), nullable=True),
    sa.Column('drawn', sa.Integer(), nullable=True),
    sa.Column('lost', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spain_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('club_name', sa.String(), nullable=True),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('won', sa.Integer(), nullable=True),
    sa.Column('drawn', sa.Integer(), nullable=True),
    sa.Column('lost', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yellow_card', sa.Integer(), nullable=True),
    sa.Column('red_card', sa.Integer(), nullable=True),
    sa.Column('shot', sa.Integer(), nullable=True),
    sa.Column('shot_on_target', sa.Integer(), nullable=True),
    sa.Column('passing', sa.Integer(), nullable=True),
    sa.Column('passing_completed', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('game', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistics_club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shots_on_target_pct', sa.Float(), nullable=True),
    sa.Column('average_shot_distance', sa.Float(), nullable=True),
    sa.Column('passes_pct', sa.Float(), nullable=True),
    sa.Column('passes_pct_short', sa.Float(), nullable=True),
    sa.Column('passes_pct_medium', sa.Float(), nullable=True),
    sa.Column('passes_pct_long', sa.Float(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('cards_yellow', sa.Integer(), nullable=True),
    sa.Column('goals_per_shot_on_target', sa.Float(), nullable=True),
    sa.Column('sca_per90', sa.Float(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics_club')
    op.drop_table('statistics')
    op.drop_table('spain_table')
    op.drop_table('italy_table')
    op.drop_table('germany_table')
    op.drop_table('france_table')
    op.drop_table('england_table')
    op.drop_table('Users')
    # ### end Alembic commands ###
