"""table_statistics

Revision ID: 72f8ea3b2ab6
Revises: b2fc82d228a7
Create Date: 2023-03-15 16:17:08.380315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f8ea3b2ab6'
down_revision = 'b2fc82d228a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics', 'country')
    # ### end Alembic commands ###
