"""table_statistics

Revision ID: b2fc82d228a7
Revises: f6b6861831c1
Create Date: 2023-03-15 15:20:35.425598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fc82d228a7'
down_revision = 'f6b6861831c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('game', sa.Integer(), nullable=True))
    op.drop_column('statistics', 'possession')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('possession', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('statistics', 'game')
    # ### end Alembic commands ###
