"""table_statistics

Revision ID: f6b6861831c1
Revises: 747c07e2e66a
Create Date: 2023-03-15 15:04:22.908320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b6861831c1'
down_revision = '747c07e2e66a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yellow_card', sa.Integer(), nullable=True),
    sa.Column('red_card', sa.Integer(), nullable=True),
    sa.Column('shot', sa.Integer(), nullable=True),
    sa.Column('shot_on_target', sa.Integer(), nullable=True),
    sa.Column('passing', sa.Integer(), nullable=True),
    sa.Column('passing_completed', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('possession', sa.Float(), nullable=True),
    sa.Column('date_add', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    # ### end Alembic commands ###
